replicaCount: 1

image:
  repository: woodjme/aws-kubectl
  tag: latest
  pullPolicy: IfNotPresent

# move creds here/pass from gitops chart
env:
  account: "983708293885"
  region: us-east-1

envSecrets:
  accessKeyId: "aws-ecr-credentials-secret"
  secretAccessKey: "aws-ecr-credentials-secret"

imagePullSecrets: aws-ecr-credentials-secret

mountSecret:
  - aws-ecr-credentials-secret

service: {}

alias: false
disableDeploy: true
healthProbes: false

ingress:
  enabled: false

resources:
  limits:
    cpu: 300m
    memory: 512Mi
  requests:
    cpu: 300m
    memory: 512Mi

nodeSelector: {}

tolerations: []

affinity: {}

persistence: []

cronJob:
  - name: cronjob
    interpolate: true
    spec:
      schedule: "* */8 * * *"
      successfulJobsHistoryLimit: 2
      failedJobsHistoryLimit: 2
      concurrencyPolicy: Forbid
      jobTemplate:
        spec:
          backoffLimit: 4
          template:
            spec:
              restartPolicy: Never
              activeDeadlineSeconds: 600
              containers:
              - name: job
                image: "{{ .Values.image.repository }}"
                tag: "{{ .Values.image.tag }}"
                args: []



