{{- if .Values.serviceAccount }}
{{- if or .Values.serviceAccount.enabled .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "Generated.fullname" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
{{- end }}