{{- if .Values.service }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "awx-operator.fullname" . }}
  {{- with .Values.service.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
  {{- end }}
  labels:
    app: {{ include "awx-operator.name" . }}
    chart: {{ include "awx-operator.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  {{- if eq .Values.service.type "ExternalName" }}
  externalName: {{ .Values.service.externalName | quote }}
  {{- else }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http
  {{- end }}
  selector:
    app: {{ include "awx-operator.name" . }}
    release: {{ .Release.Name }}
{{- end }}
