replicaCount: 1

image:
  repository: 983708293885.dkr.ecr.us-east-1.amazonaws.com/sample-app
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

imagePullSecrets: 
  - aws-registry

service:
  type: ClusterIP
  port: 80
  annotations: {}
  labels: {}

healthProbes: false

ingress:
  enabled: false

resources:
 limits:
   cpu: 300m
   memory: 512Mi
 requests:
   cpu: 300m
   memory: 512Mi

nodeSelector: {}

tolerations: []

affinity: {}

# Enable autoscaling
autoscaling:
  enabled: false

