replicaCount: 1

image:
  repository: 983708293885.dkr.ecr.us-east-1.amazonaws.com/sample-app
  tag: sandbox
  pullPolicy: IfNotPresent

imagePullSecrets:
  - aws-ecr-credentials

service:
  type: ClusterIP
  port: 80
  annotations: {}
  labels: {}

healthProbes: false

ingress:
  enabled: false

resources:
 limits:
   cpu: 300m
   memory: 512Mi
 requests:
   cpu: 300m
   memory: 512Mi

nodeSelector: {}

tolerations: []

affinity: {}

# Enable autoscaling
autoscaling:
  enabled: false

