{{- if .Values.rbac.create -}}
{{- $gName := include "Generated.fullname" .}}
{{- $gChart := include "Generated.chart" . }}
{{- $gReleaseName := .Release.Name }}
{{- $gHeritage := .Release.Service }}
{{- $version := .Values.image.tag }}
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: {{ $gName }}
  labels:
    app: {{ $gName }}
    chart: {{ $gChart }}
    release: {{ $gReleaseName }}
    heritage: {{ $gHeritage }}
    version: {{ $version | default "0" | quote }}
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "create", "delete"]
- apiGroups: [""]
  resources: ["serviceaccounts"]
  verbs: ["get", "patch"]
{{- end -}}

