{{- if .Values.serviceAccount }}
{{- if .Values.serviceAccount.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "Generated.fullname" . }}
  namespace: {{ $.Release.Namespace }}
{{- end }}
{{- end }}
