{{- if .Values.serviceAccount }}
{{- if .Values.serviceAccount.enabled }}
{{- $gName := include "Generated.fullname" .}}
{{- $gChart := include "Generated.chart" . }}
{{- $gReleaseName := .Release.Name }}
{{- $gHeritage := .Release.Service }}
{{- $version := .Values.image.tag }}
{{- $nameSpace :=.Release.Namespace }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $gName }}
  namespace: {{ $nameSpace }}
  labels:
    app: {{ $gName }}
    chart: {{ $gChart }}
    release: {{ $gReleaseName }}
    heritage: {{ $gHeritage }}
    version: {{ $version | default "0" | quote }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ $gName }}
  labels:
    app: {{ $gName }}
    chart: {{ $gChart }}
    release: {{ $gReleaseName }}
    heritage: {{ $gHeritage }}
    version: {{ $version | default "0" | quote }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: {{ $gName }}
    namespace: {{ $nameSpace }}
{{- end }}
{{- end }}


