replicaCount: 1

image:
  repository: joemsanc/icd10codesapi
  tag: 1.0.0
  pullPolicy: IfNotPresent

imagePullSecrets:
  - dockerregcred

env:
  name: test

service:
  type: ClusterIP
  port: 80
  annotations: {}
  labels: {}

alias: false
healthProbes: false

ingress:
  enabled: true
  path: /icd10codesapi
  hosts:
  - testservices.emrops.com
  tls:
  - secretName: tls-star-emrops
    hosts:
    - testservices.emrops.com
  ambassador:
    enabled: true
    ambassador_id: ambassador-id
    prefix: /icd10codesapi/
    rewrite: /
    timeout_ms: 60000
    connect_timeout_ms: 60000
    apiVersion: getambassador.io/v1

resources:
  limits:
    cpu: 300m
    memory: 512Mi
  requests:
    cpu: 300m
    memory: 512Mi

nodeSelector: {}

tolerations: []

affinity: {}

persistence: []

