replicaCount: 1

image:
  repository: joemsanc/icd10codesapi
  tag: 1.0.0
  pullPolicy: IfNotPresent

imagePullSecrets:
  - dockerregcred

env:
  DbUserId: devdbuser
  DbPassword: develop

service:
  type: ClusterIP
  port: 80
  annotations: {}
  labels: {}

alias: false
healthProbes: false

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/affinity: "cookie"
    nginx.ingress.kubernetes.io/session-cookie-name: "icd10codes-api"
    nginx.ingress.kubernetes.io/session-cookie-hash: "sha1"
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/add-base-url: "true"
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-origin: "*"
  path: /icd10codesapi
  hosts:
    - testservices.emrops.com
  tls:
  - secretName: tls-star-emrops
    hosts:
    - testservices.emrops.com

resources:
  limits:
    cpu: 300m
    memory: 512Mi
  requests:
    cpu: 300m
    memory: 512Mi

nodeSelector: {}

tolerations: []

affinity: {}

persistence: []

