replicaCount: 1

image:
  repository: "https://cloud.docker.com/repository/docker/joemsanc/wallboard/general"
  tag: "tagname"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

alias: true
healthProbes: true

ingress:
  enabled: true
  annotations: 
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/affinity: "cookie"
    nginx.ingress.kubernetes.io/session-cookie-name: "care-quality"
    nginx.ingress.kubernetes.io/session-cookie-hash: "sha1"
    nginx.ingress.kubernetes.io/add-base-url: "true"

  path: /carequality
  hosts:
    - devservices.practicevelocity.com
  tls:
    - secretName: tls-star-practicevelocity
      hosts:
        - devservices.practicevelocity.com

resources:
  limits:
    cpu: 300m
    memory: 512Mi
  requests:
    cpu: 300m
    memory: 512Mi

nodeSelector: {}

tolerations: []

affinity: {}

