replicaCount: 1

image:
  repository: "hub.pvops.com/dev/care-quality"
  tag: "19.1.20190309124339"
  pullPolicy: IfNotPresent

env:
  PathBase: "carequality"
  RcmApiBaseAddress: "http://rcm-admin-api-alias/"
  ASPNETCORE_ENVIRONMENT: "Production"
  ASPNETCORE_URLS: "http://0.0.0.0:80"
  KeyFilePath: "/var/secret"
  EncryptionPrivateKeyFileName: "EncryptionPrivateKey"
  EncryptionPrivateKeyFilePath: "/var/secret"
  EncryptionPublicKeyFileName: "EncryptionPublicKey"
  EncryptionPublicKeyFilePath: "/var/secret"

envSecrets:
  RcmApiUserName: "care-quality-credentials"
  RcmApiPassword: "care-quality-credentials"
  APP_SECRET: "care-quality-credentials"
  EncryptionPrivateKey: "care-quality-credentials"
  EncryptionPublicKey: "care-quality-credentials"

mountSecret:
  - care-quality-credentials

envConfigurations:
  IntegrationApiBaseAddress: "care-quality-configurations"
  CareQualityBaseAddress: "care-quality-configurations"
  AppAuthApiBaseAddress: "care-quality-configurations"
  SignalRServerApiUrl: "care-quality-configurations"
 
service:
  type: ClusterIP
  port: 80

alias: true
healthProbes: true

ingress:
  enabled: true
  annotations: 
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/affinity: "cookie"
    nginx.ingress.kubernetes.io/session-cookie-name: "care-quality"
    nginx.ingress.kubernetes.io/session-cookie-hash: "sha1"
    nginx.ingress.kubernetes.io/add-base-url: "true"

  path: /carequality
  hosts:
    - devservices.practicevelocity.com
  tls:
    - secretName: tls-star-practicevelocity
      hosts:
        - devservices.practicevelocity.com

resources:
  limits:
    cpu: 300m
    memory: 512Mi
  requests:
    cpu: 300m
    memory: 512Mi

nodeSelector: {}

tolerations: []

affinity: {}

