replicaCount: 1

image:
  repository: proget.medicomp.com/medicomp-docker/medcin-server
  tag: 2.22.20203.718
  pullPolicy: IfNotPresent

env:
  MEDCIN_SERVER_PORT: 80
  MEDCIN_LICENSE_FILE_PATH: "/var/data/medicomp/medcin"
  MEDCIN_LICENSE_FILE: "medcin.lic"

envSecrets:
  MEDCIN_LICENSE_SECRET: "test-medcin-license"

mountSecret:
  - test-medcin-license

service:
  type: ClusterIP
  port: 80
  annotations: {}
  labels: {}

alias: true
healthProbes: false

ingress:
  enabled: true
  annotations: {}

server:
  statefulSet:
    enabled: true
  persistentVolume:
    size: 20Gi
    storageClass: "data-delete-sc"

resources:
  limits:
    cpu: 300m
    memory: 512Mi
  requests:
    cpu: 300m
    memory: 512Mi

nodeSelector: {}

tolerations: []

affinity: {}

# Enable autoscaling 
autoscaling:
  enabled: false
  minReplicas: 2
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 60  



