apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: awx-pvc
  namespace: awx
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 12Gi
  storageClassName: data-retain-sc
