replicaCount: 1

image:
  repository: quay.io/ansible/awx-operator
  tag: 0.7.0
  pullPolicy: IfNotPresent

env:
  # Watch all namespaces (cluster-scoped).
  - name: WATCH_NAMESPACE
    value: ""
  - name: POD_NAME
    valueFrom:
      fieldRef:
        fieldPath: metadata.name
  - name: OPERATOR_NAME
    value: awx-operator
  - name: ANSIBLE_GATHERING
    value: explicit

envSecrets:
  # MEDCIN_LICENSE_SECRET: "test-medcin-license"

mountSecret:
  # - test-medcin-license

service:
  type: ClusterIP
  port: 80
  annotations: {}
  labels: {}

alias: true
healthProbes: false

ingress:
  enabled: false
  annotations: {}

server:
  statefulSet:
    enabled: true
  persistentVolume:
    size: 20Gi
    storageClass: "data-delete-sc"

resources:
  limits:
    cpu: 300m
    memory: 512Mi
  requests:
    cpu: 300m
    memory: 512Mi

nodeSelector: {}

tolerations: []

affinity: {}

volumeMounts: {}
  # - mountPath: /tmp/ansible-operator/runner
  #   name: runner

# Enable autoscaling 
autoscaling:
  enabled: false
