# Authentication settings
# Valid values for enabled_auth_method are `none`, `password`, and `openId`.
auth:
  enabledMethod: password
#  password: ""
#  openId:
#    issuerBaseUrl: ""
#    clientId: ""
#    baseUrl: ""
#    secret: ""
#    groupClaim: ""
#    userGroup: ""

replicaCount: 1

image:
  repository: quay.io/ansible/awx-operator
  tag: '0.9.0'
  pullPolicy: Always

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
hostnameOverride: ""
namespace: "awx"

ingress:
  enabled: false

rbac:
  create: true
  namespaced: true

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

service:
  type: ClusterIP
  port: 80

livenessProbe:
  httpGet:
    path: /healthz
    port: 6789
  initialDelaySeconds: 15
  periodSeconds: 20

server:
  statefulSet:
    enabled: true
  persistentVolume:
    size: 8Gi
    storageClass: "data-delete-sc"

# # volumeMounts:
# #   - mountPath: /tmp/ansible-operator/runner
# #     name: runner

# volumes:
#   - name: runner
#     emptyDir: {}

# persistence: {}
#   # - name: awx-vol
#     # enabled: false
#     # mountPath: /tmp/ansible-operator/runner
#     # spec:
#     #   storageClass: "data-delete-sc"
#     #   accessModes:
#     #    - ReadWriteOnce
#     #   volumeMode: Filesystem
#     #   resources:
#     #     requests:
#     #       storage: 8Gi

##
## Init containers parameters:
## volumePermissions: Change the owner of the persist volume mountpoint to RunAsUser:fsGroup
##
volumePermissions:
  enabled: true
  securityContext:
    runAsUser: 0

## Pod Security Context
## ref: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/
##
securityContext:
  enabled: true
  fsGroup: 1000
  runAsUser: 1000

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

