replicaCount: 1

image:
  repository: hub.emrops.com/external/aws-cli
  tag: 1.19.5
  pullPolicy: IfNotPresent

env:
  account: "983708293885"
  region: us-east-1

envSecrets:
  aws_access_key_id: "aws-ecr-credentials"
  aws_secret_access_key: "aws-ecr-credentials"

secret:
  external: true
  prefix: /hq/k8s/devops-dev

serviceAccount:
  create: true
  name: "aws-ecr"

service: {}

alias: false
disableDeploy: true
healthProbes: false

ingress:
  enabled: false

resources:
  limits:
    cpu: 300m
    memory: 512Mi
  requests:
    cpu: 300m
    memory: 512Mi

nodeSelector: {}

tolerations: []

affinity: {}

persistence: []

cronJob:
  - name: cronjob
    interpolate: true
    spec:
      schedule: "* */8 * * *"
      successfulJobsHistoryLimit: 2
      failedJobsHistoryLimit: 2
      concurrencyPolicy: Forbid
      jobTemplate:
        spec:
          backoffLimit: 4
          template:
            spec:
              restartPolicy: Never
              activeDeadlineSeconds: 600
              containers:
                - name: job
                  image: "{{ .Values.image.repository }}"
                  tag: "{{ .Values.image.tag }}"
                  command:
                  - "/bin/sh"
                  - "-c"
                  - |
                    AWS_ACCOUNT="{{ .Values.env.account }}"
                    AWS_REGION="{{ .Values.env.region }}"
                    echo "AWS_ACCOUNT=$AWS_ACCOUNT"
                    echo "AWS_REGION=$AWS_REGION"

